- name: Demo on using variables
  hosts: all
  vars:                                             # Declaring variables at play level; All tasks of play can access this variable URL
    URL: play.google.com
  vars_files:
      demo-vars.yaml
  vars_prompt:
    - name: URL 
      prompt: Enter URL Value 
      private: false

  tasks:
    - name: Printing URL
      ansible.builtin.debug:
        msg: "{{URL}}"

    - name: Printing URLs
      ansible.builtin.debug:
        msg: Value of URL is {{URL}}
      vars:                                        # Declaring the variable at task level ( local variable)
        URL: task.google.com

    - name: Printing CLI_URL
      ansible.builtin.debug:
        msg: Value of CLI_URL is "{{CLI_URL}}"


# How do you print a variable in bash ???? ${varName}
# To print a variable in yaml, we will use {{varName}}

# Variable name has to be enclosed in quotes only if it is only entity in the message, if not you can just enclose them in quotes.
# Always prefer to keep the task name different, In version 6, it used to throw error, In version 7, htats deprecated

# Ansible throws you an error if you use a variable that is not declared ; In bash, it assumes it as a empty variable

# CLI Variable > Local Variable > Files Variables >  Global Variable > Prompt Variable