# A fact is nothis but a property of the machine - node extrcted by the ansible server


- name: Demo on facts
  hosts: all
  tasks:
    - name: task1
      ansible.builtin.debug:
        msg: OS Distribution = {{ansible_distribution}}

    # - name: 
    #   ansible.builtin.debug:
    #     msg: 
