- name: Demo on shell module
  hosts: all
  tasks:
    - name: Execute shell Command
      ansible.builtin.shell: uptime
      register: OUT                    # Register captures the output of the shell command and pressure it is the variable with name of our choice.

    - name: Execute shell Command
      ansible.builtin.debug:
        msg: "{{OUT.stdout}}"