- name: Demo on Loops
  hosts: all
  tasks:
    - name: Printing a Loops
      ansible.builtin.debug:
        msg: Value in the loop is "{{item}}"
      loop:
        - 10
        - 20
        - 30
        - 40
        - 50

# Values in the loop can be referred by the key word / variable "item"