- name: Install Nginx
  ansible.builtin.package:
    name: nginx
    state: present

- name: Download and extracting
  ansible.builtin.unarchive:
    src: "https://github.com/stans-robot-project/frontend/archive/main.zip"
    dest: /tmp
    remote_src: yes           # remote_src: yes: yes tells that the source to be downloaded/copied is not localy available

- name: Clearing old HTML content
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Copy the Frontend Cntant to Nginx path
  ansible.builtin.copy:
    src: /tmp/frintend-main/static/
    dest: /usr/share/nginx/html/
    remote_src: yes           # Since the remote is on a remote machine, ensure you mention remote_src as yes

- name: Copy Nginx Config
  ansible.builtin.copy:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf