- name: Configuring NodeJs Repo
  ansible.builtin.shell: curl --silent --location https://rpm.nodesource.com/setup_16.x | sudo bash -

- name: Install Nodejs
  ansible.builtin.package:
    name: nodejs
    state: present

- name: Creating the application user account
  ansible.builtin.user:
    name: "{{APPUSER}}"
    comment: roboshop service account

- name: Download and extracting the catalogue
  ansible.builtin.unarchive:
    src: "https://github.com/stans-robot-project/{{COMPONENT}}/archive/main.zip"
    dest: /tmp
    remote_src: yes

- name: Cleanup of old content
  ansible.builtin.file:
    path: /home/{{APPUSER}}/{{COMPONENT}}/
    state: absent

- name: Copy files to the roboshop home directory
  ansible.builtin.copy:
    src: /tmp/{{COMPONENT}}-main/
    dest: /home/{{APPUSER}}/{{COMPONENT}}/
    remote_src: yes
    owner: "{{APPUSER}}"
    group: "{{APPUSER}}"

- name: Installing NodeJs package
  community.general.npm:
    path: /home/{{APPUSER}}/{{COMPONENT}}/

- name: Copying Systemd service file
  ansible.builtin.copy:
    src: systemd.service
    dest: /etc/systemd/system/catalogue.service
    owner: "{{APPUSER}}"
    group: "{{APPUSER}}"
